#!/usr/bin/env python3

from argparse import ArgumentParser

def read_json(filename):
	pass

def moving_average():
	return 1

def calculate_averages():
	pass



#Read arguments
parser = ArgumentParser()
parser.add_argument("-i", "--input_file", dest="filename",
            help="json input file", metavar="FILE")
parser.add_argument("-w", "--window_size", dest="window_size",
            help="window size for the moving average")

args = parser.parse_args()

#Check for missing arguments
if args.filename is None or args.window_size is None:
	parser.print_help()


